.TH "C:/Users/Stefan/Documents/GitHub/Final_Project Directory Reference" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/Final_Project Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcontrollers\fP"
.br
.ti -1c
.RI "directory \fBlib\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBepuck`_movement_download\&.c\fP"
.br
.ti -1c
.RI "file \fBmap_building\&.c\fP"
.br
.ti -1c
.RI "file \fBodometry\&.c\fP"
.br
.ti -1c
.RI "file \fBscanline_backup\&.c\fP"
.br
.in -1c
