.TH "C:/Users/Stefan/Documents/GitHub/Final_Project/controllers Directory Reference" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/Final_Project/controllers Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBe_puck_movement\fP"
.br
.ti -1c
.RI "directory \fBepuck_collision_avoidance\fP"
.br
.ti -1c
.RI "directory \fBepuck_scanline\fP"
.br
.ti -1c
.RI "directory \fBMain\fP"
.br
.ti -1c
.RI "directory \fBmid_term_demo\fP"
.br
.ti -1c
.RI "directory \fBmy_controller_epuk_go_forward\fP"
.br
.in -1c
