.TH "C:/Users/Stefan/Documents/GitHub/Final_Project/controllers/epuck_collision_avoidance/build Directory Reference" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/Final_Project/controllers/epuck_collision_avoidance/build Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBrelease\fP"
.br
.in -1c
