.TH "C:/Users/Stefan/Documents/GitHub/Final_Project/controllers/epuck_scanline/epuck_scanline.c" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/Final_Project/controllers/epuck_scanline/epuck_scanline.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <webots/robot\&.h>\fP
.br
\fC#include <webots/distance_sensor\&.h>\fP
.br
\fC#include <webots/differential_wheels\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTHRESHOLD_DIST\fP   300"
.br
.ti -1c
.RI "#define \fBTIME_STEP\fP   32"
.br
.ti -1c
.RI "#define \fBSIMULATION\fP   0"
.br
.ti -1c
.RI "#define \fBREALITY\fP   2"
.br
.ti -1c
.RI "#define \fBLEFT\fP   0"
.br
.ti -1c
.RI "#define \fBRIGHT\fP   1"
.br
.ti -1c
.RI "#define \fBNB_DIST_SENS\fP   8"
.br
.ti -1c
.RI "#define \fBPS_RIGHT_10\fP   0"
.br
.ti -1c
.RI "#define \fBPS_RIGHT_45\fP   1"
.br
.ti -1c
.RI "#define \fBPS_RIGHT_90\fP   2"
.br
.ti -1c
.RI "#define \fBPS_RIGHT_REAR\fP   3"
.br
.ti -1c
.RI "#define \fBPS_LEFT_REAR\fP   4"
.br
.ti -1c
.RI "#define \fBPS_LEFT_90\fP   5"
.br
.ti -1c
.RI "#define \fBPS_LEFT_45\fP   6"
.br
.ti -1c
.RI "#define \fBPS_LEFT_10\fP   7"
.br
.ti -1c
.RI "#define \fBWHEEL_RADIUS\fP   0\&.02"
.br
.ti -1c
.RI "#define \fBAXLE_LENGTH\fP   0\&.026"
.br
.ti -1c
.RI "#define \fBENCODER_RESOLUTION\fP   159\&.23"
.br
.ti -1c
.RI "#define \fBFORWARD\fP   0"
.br
.ti -1c
.RI "#define \fBSTOP\fP   1"
.br
.ti -1c
.RI "#define \fBUTURN\fP   2"
.br
.ti -1c
.RI "#define \fBTURNRIGHT\fP   3"
.br
.ti -1c
.RI "#define \fBTURNLEFT\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "WbDeviceTag \fBps\fP [\fBNB_DIST_SENS\fP]"
.br
.ti -1c
.RI "int \fBps_value\fP [\fBNB_DIST_SENS\fP] ={0,0,0,0,0,0,0,0}"
.br
.ti -1c
.RI "int \fBps_offset_sim\fP [\fBNB_DIST_SENS\fP] = {35,35,35,35,35,35,35,35}"
.br
.ti -1c
.RI "int \fBps_offset_real\fP [\fBNB_DIST_SENS\fP] = {375,158,423,682,447,594,142,360}"
.br
.ti -1c
.RI "int \fBobstacle\fP [\fBNB_DIST_SENS\fP]"
.br
.ti -1c
.RI "int \fBspeed\fP [2] = {0,0}"
.br
.ti -1c
.RI "int \fBstate\fP = \fBFORWARD\fP"
.br
.ti -1c
.RI "int \fBn\fP =0"
.br
.ti -1c
.RI "int \fBold_encoder\fP =0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AXLE_LENGTH   0\&.026"

.SS "#define ENCODER_RESOLUTION   159\&.23"

.SS "#define FORWARD   0"

.SS "#define LEFT   0"

.SS "#define NB_DIST_SENS   8"

.SS "#define PS_LEFT_10   7"

.SS "#define PS_LEFT_45   6"

.SS "#define PS_LEFT_90   5"

.SS "#define PS_LEFT_REAR   4"

.SS "#define PS_RIGHT_10   0"

.SS "#define PS_RIGHT_45   1"

.SS "#define PS_RIGHT_90   2"

.SS "#define PS_RIGHT_REAR   3"

.SS "#define REALITY   2"

.SS "#define RIGHT   1"

.SS "#define SIMULATION   0"

.SS "#define STOP   1"

.SS "#define THRESHOLD_DIST   300"

.SS "#define TIME_STEP   32"

.SS "#define TURNLEFT   4"

.SS "#define TURNRIGHT   3"

.SS "#define UTURN   2"

.SS "#define WHEEL_RADIUS   0\&.02"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Variable Documentation"
.PP 
.SS "int n =0"

.SS "int obstacle[\fBNB_DIST_SENS\fP]"

.SS "int old_encoder =0"

.SS "WbDeviceTag ps"

.SS "int ps_offset_real[\fBNB_DIST_SENS\fP] = {375,158,423,682,447,594,142,360}"

.SS "int ps_offset_sim[\fBNB_DIST_SENS\fP] = {35,35,35,35,35,35,35,35}"

.SS "int ps_value[\fBNB_DIST_SENS\fP] ={0,0,0,0,0,0,0,0}"

.SS "int speed[2] = {0,0}"

.SS "int state = \fBFORWARD\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Major Project Documentation from the source code\&.
