.TH "C:/Users/Stefan/Documents/GitHub/Final_Project/map_building.c" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/Final_Project/map_building.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <webots/robot\&.h>\fP
.br
\fC#include <webots/differential_wheels\&.h>\fP
.br
\fC#include <webots/distance_sensor\&.h>\fP
.br
\fC#include <webots/light_sensor\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <webots/display\&.h>\fP
.br
\fC#include 'map_building\&.h'\fP
.br
\fC#include 'e_puck_movement\&.h'\fP
.br
\fC#include 'odometry\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIME_STEP\fP   8"
.br
.ti -1c
.RI "#define \fBMAP_SIZE\fP   70"
.br
.ti -1c
.RI "#define \fBCELL_SIZE\fP   0\&.015"
.br
.ti -1c
.RI "#define \fBTHRESHOLD_DIST\fP   100"
.br
.ti -1c
.RI "#define \fBOCCUPANCE_DIST\fP   150"
.br
.ti -1c
.RI "#define \fBLEFT\fP   0"
.br
.ti -1c
.RI "#define \fBRIGHT\fP   1"
.br
.ti -1c
.RI "#define \fBNUM_DIST_SENS\fP   8"
.br
.ti -1c
.RI "#define \fBPS_RIGHT_10\fP   0"
.br
.ti -1c
.RI "#define \fBPS_RIGHT_45\fP   1"
.br
.ti -1c
.RI "#define \fBPS_RIGHT_90\fP   2"
.br
.ti -1c
.RI "#define \fBPS_RIGHT_REAR\fP   3"
.br
.ti -1c
.RI "#define \fBPS_LEFT_REAR\fP   4"
.br
.ti -1c
.RI "#define \fBPS_LEFT_90\fP   5"
.br
.ti -1c
.RI "#define \fBPS_LEFT_45\fP   6"
.br
.ti -1c
.RI "#define \fBPS_LEFT_10\fP   7"
.br
.ti -1c
.RI "#define \fBFORWARD\fP   0"
.br
.ti -1c
.RI "#define \fBTURNRIGHT\fP   1"
.br
.ti -1c
.RI "#define \fBTURNLEFT\fP   2"
.br
.ti -1c
.RI "#define \fBUTURN\fP   3"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_display\fP ()"
.br
.ti -1c
.RI "void \fBoccupied_cell\fP (int x, int y, float theta)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP (struct \fBodometryTrackStruct\fP *\fBot\fP)"
.br
.ti -1c
.RI "int * \fBreturn_sensor_values\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "WbDeviceTag \fBled\fP [3]"
.br
.ti -1c
.RI "WbDeviceTag \fBps\fP [\fBNUM_DIST_SENS\fP]"
.br
.ti -1c
.RI "WbDeviceTag \fBdisplay\fP"
.br
.ti -1c
.RI "WbImageRef \fBbackground\fP"
.br
.ti -1c
.RI "int \fBdisplay_width\fP"
.br
.ti -1c
.RI "int \fBdisplay_height\fP"
.br
.ti -1c
.RI "int \fBmap\fP [\fBMAP_SIZE\fP][\fBMAP_SIZE\fP]"
.br
.ti -1c
.RI "int \fBrobot_x\fP = \fBMAP_SIZE\fP / 2"
.br
.ti -1c
.RI "int \fBrobot_y\fP = \fBMAP_SIZE\fP / 2"
.br
.ti -1c
.RI "int \fBps_value\fP [\fBNUM_DIST_SENS\fP] ={0,0,0,0,0,0,0,0}"
.br
.ti -1c
.RI "int \fBobstacle\fP [\fBNUM_DIST_SENS\fP] ={0,0,0,0,0,0,0,0}"
.br
.ti -1c
.RI "bool \fBob_front\fP"
.br
.ti -1c
.RI "bool \fBob_right\fP"
.br
.ti -1c
.RI "bool \fBob_left\fP"
.br
.ti -1c
.RI "float \fBangle_offset\fP [\fBNUM_DIST_SENS\fP] = {0\&.2793, 0\&.7854, 1\&.5708, 2\&.618, -2\&.618, -1\&.5708, -0\&.7854, -0\&.2793}"
.br
.ti -1c
.RI "int \fBnew_encoder\fP"
.br
.ti -1c
.RI "int \fBstate\fP = \fBFORWARD\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CELL_SIZE   0\&.015"

.SS "#define FORWARD   0"

.SS "#define LEFT   0"

.SS "#define MAP_SIZE   70"

.SS "#define NUM_DIST_SENS   8"

.SS "#define OCCUPANCE_DIST   150"

.SS "#define PS_LEFT_10   7"

.SS "#define PS_LEFT_45   6"

.SS "#define PS_LEFT_90   5"

.SS "#define PS_LEFT_REAR   4"

.SS "#define PS_RIGHT_10   0"

.SS "#define PS_RIGHT_45   1"

.SS "#define PS_RIGHT_90   2"

.SS "#define PS_RIGHT_REAR   3"

.SS "#define RIGHT   1"

.SS "#define THRESHOLD_DIST   100"

.SS "#define TIME_STEP   8"

.SS "#define TURNLEFT   2"

.SS "#define TURNRIGHT   1"

.SS "#define UTURN   3"

.SH "Function Documentation"
.PP 
.SS "void init_display ()"
Initiate the display with a white color 
.SS "void occupied_cell (intx, inty, floattheta)"
Set the coresponding cell to 1 (occuM_PIed) and display it 
.SS "void reset (void)"
enables the needed sensor devices 
.SS "int* return_sensor_values ()"
returns a pointer to an array of the current sensor values 
.SS "void run (struct \fBodometryTrackStruct\fP *ot)"

.SH "Variable Documentation"
.PP 
.SS "float angle_offset[\fBNUM_DIST_SENS\fP] = {0\&.2793, 0\&.7854, 1\&.5708, 2\&.618, -2\&.618, -1\&.5708, -0\&.7854, -0\&.2793}"

.SS "WbImageRef background"

.SS "WbDeviceTag display"

.SS "int display_height"

.SS "int display_width"

.SS "WbDeviceTag led[3]"

.SS "int map[\fBMAP_SIZE\fP][\fBMAP_SIZE\fP]"

.SS "int new_encoder"

.SS "bool ob_front"

.SS "bool ob_left"

.SS "bool ob_right"

.SS "int obstacle[\fBNUM_DIST_SENS\fP] ={0,0,0,0,0,0,0,0}"

.SS "WbDeviceTag ps[\fBNUM_DIST_SENS\fP]"

.SS "int ps_value[\fBNUM_DIST_SENS\fP] ={0,0,0,0,0,0,0,0}"

.SS "int robot_x = \fBMAP_SIZE\fP / 2"

.SS "int robot_y = \fBMAP_SIZE\fP / 2"

.SS "int state = \fBFORWARD\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Major Project Documentation from the source code\&.
