.TH "C:/Users/Stefan/Documents/GitHub/Final_Project/lib/map_building.h" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/Final_Project/lib/map_building.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_display\fP ()"
.br
.ti -1c
.RI "void \fBoccupied_cell\fP (int x, int y, float theta)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "int * \fBreturn_sensor_values\fP ()"
.br
.ti -1c
.RI "int \fBreturn_angle\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void init_display ()"
Initiate the display with a white color 
.SS "void occupied_cell (intx, inty, floattheta)"
Set the coresponding cell to 1 (occuM_PIed) and display it 
.SS "void reset (void)"
enables the needed sensor devices 
.SS "int return_angle ()"

.SS "int* return_sensor_values ()"
returns a pointer to an array of the current sensor values 
.SS "void run ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Major Project Documentation from the source code\&.
