.TH "C:/Users/Stefan/Documents/GitHub/Final_Project/controllers/my_controller_epuk_go_forward/my_controller_epuk_go_forward.c" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/Final_Project/controllers/my_controller_epuk_go_forward/my_controller_epuk_go_forward.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <webots/robot\&.h>\fP
.br
\fC#include <webots/differential_wheels\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIME_STEP\fP   64"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIME_STEP   64"

.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Major Project Documentation from the source code\&.
