.TH "odometryTrackStruct" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
odometryTrackStruct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <odometry\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   float \fBwheel_distance\fP"
.br
.ti -1c
.RI "   float \fBwheel_conversion\fP"
.br
.ti -1c
.RI "} \fBconfiguration\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBpos_left_prev\fP"
.br
.ti -1c
.RI "   int \fBpos_right_prev\fP"
.br
.ti -1c
.RI "} \fBstate\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   float \fBx\fP"
.br
.ti -1c
.RI "   float \fBy\fP"
.br
.ti -1c
.RI "   float \fBtheta\fP"
.br
.ti -1c
.RI "} \fBresult\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. }   configuration"

.SS "int pos_left_prev"

.SS "int pos_right_prev"

.SS "struct { \&.\&.\&. }   result"

.SS "struct { \&.\&.\&. }   state"

.SS "float theta"

.SS "float wheel_conversion"

.SS "float wheel_distance"

.SS "float x"

.SS "float y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Major Project Documentation from the source code\&.
