.TH "C:/Users/Stefan/Documents/GitHub/Final_Project/lib/odometry.h" 3 "Mon Mar 31 2014" "Version 0.2" "Major Project Documentation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Stefan/Documents/GitHub/Final_Project/lib/odometry.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBodometryTrackStruct\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBodometry_track_start\fP (struct \fBodometryTrackStruct\fP *\fBot\fP)"
.br
.ti -1c
.RI "int \fBodometry_track_start_pos\fP (struct \fBodometryTrackStruct\fP *\fBot\fP, double *dEncPos)"
.br
.ti -1c
.RI "void \fBodometry_track_step\fP (struct \fBodometryTrackStruct\fP *\fBot\fP)"
.br
.ti -1c
.RI "void \fBodometry_track_step_pos\fP (struct \fBodometryTrackStruct\fP *\fBot\fP, double *dEncPos)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int odometry_track_start (struct \fBodometryTrackStruct\fP *ot)"
Initializes the odometry algortihms 
.SS "int odometry_track_start_pos (struct \fBodometryTrackStruct\fP *ot, double *dEncPos)"
Start the odometry tracking Updates the info in the \fBodometryTrackStruct\fP for the first time 
.SS "void odometry_track_step (struct \fBodometryTrackStruct\fP *ot)"

.SS "void odometry_track_step_pos (struct \fBodometryTrackStruct\fP *ot, double *dEncPos)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Major Project Documentation from the source code\&.
